baseURL : "https://dmaziyo.github.io"
languageCode : "en-us"
title : "MaZiYo's Blog"
theme: PaperMod
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true

paginate: 15    # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°


params:
    homeInfoParams:
        Title: "Dct MaZiYo"
        Content: >
            Iâ€™m a college student majoring in CS,  i'm passionate on front-end ,open source culture and enjoy building interesting stuff, Outside of programming. i enjoyğŸ•¹ï¸video games,ğŸ§¢hiphop,ğŸ¸ and all sort of sports
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    author: MaZiYo
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    hideFooter: false # éšè—é¡µè„š
    ShowWordCounts: true
    VisitCount: true

    ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´

    ShowToc: true # æ˜¾ç¤ºç›®å½•
    TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
    socialIcons:
      - name: twitter
        title: twitter
        url: "https://twitter.com/DctZi"
      - name: github
        title: github
        url: "https://github.com/Dmaziyo"


menu:
  main:
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: Blogs
      name: Blog
      url: /posts/
      weight: 20
      